import { createSlice } from "@reduxjs/toolkit";
import { getContryData } from "../actions";

// Initial state for the country data slice
const initialState = {
  data: [], // Array to hold country data
  isLoading: false, // Flag to indicate loading state
  isSuccess: false, // Flag to indicate success state
  errorMessage: "", // Error message in case of failure
};

// Create a Redux slice for managing country data
export const contrySlice = createSlice({
  name: "contry", // Slice name
  initialState, // Initial state defined above
  extraReducers: {
    // Handle pending action (data is being fetched)
    [getContryData.pending]: (state) => {
      state.isLoading = true; // Set loading flag to true
    },
    // Handle fulfilled action (data fetching is successful)
    [getContryData.fulfilled]: (state, { payload }) => {
      state.isLoading = false; // Set loading flag to false
      state.isSuccess = true; // Set success flag to true
      state.data = payload; // Update country data in the state
    },
    // Handle rejected action (data fetching has failed)
    [getContryData.rejected]: (state, { payload }) => {
      state.isLoading = false; // Set loading flag to false
      state.isSuccess = false; // Set success flag to false
      state.errorMessage = payload; // Update error message in the state
    },
  },
});

// Export the reducer function generated by createSlice
export default contrySlice.reducer;
